// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationMapController from "./location_map_controller"
application.register("location-map", LocationMapController)

import MessagesController from "./messages_controller"
application.register("messages", MessagesController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SpellThisController from "./spell_this_controller"
application.register("spell-this", SpellThisController)
