// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GreenbgController from "./greenbg_controller"
application.register("greenbg", GreenbgController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SpellThisController from "./spell_this_controller"
application.register("spell-this", SpellThisController)
